services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JWT_SECRET=${JWT_SECRET}
        - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped
    networks:
      - museu_network
networks:
  museu_network:
    external: true

volumes:
  uploads_data:
