services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
