services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/database_museu
    command: sleep infinity
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: museu_db_dev
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_museu
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
