name: Deploy on New Tag

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH Commands
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.HOST }}
        username: siteextensao
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/siteextensao/ProjetoMuseu
          git pull origin main
          sudo docker compose down
          sudo docker compose build --no-cache
          sudo docker compose up -d
